server:
  port: ${SERVER_PORT:8080}
spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver